### ISSUE TITLE
About DialogueRNN performance Prob.

### ISSUE THREAD

**Issue by Columbine21** [declare-lab/dialogue-understanding#3]
Yours DialogueRNN performance:（in your endtoend implement, **Bidirection & attention on emotion strategy** are used.）
<img width="827" alt="截屏2020-10-12 上午10 41 22" src="https://user-images.githubusercontent.com/46373350/95699601-7a740f00-0c77-11eb-9081-be59984ba40a.png">
Original DialogueRNN performance:
<img width="795" alt="1" src="https://user-images.githubusercontent.com/46373350/95700206-033f7a80-0c79-11eb-87fe-6e85de2c3918.png">

#### From Above, your implement of DialogueRNN is worse than the original paper?

**Comment by deepanwayx** [comment]
There are some difference in the results because the training strategy is somewhat different. The earlier DialogueRNN model was trained in a two-stage setup which generally gives slightly better results. For the new models in this repo, we have implemented all models end-to-end to make the training and all the different kinds of evaluation strategies more flexible. 

We observed some variance in the results for the GloVe models in the end-to-end setup. We write about these observations in Section 5, page 12 of our paper. For this reason, we ran each model more than 20 times and average their results in Table 3 and 4.

**Comment by Columbine21** [comment]
Thanks a lot.By the way, what about the earlier DialogueRNN model (trained in two-stage setup), would you like share the W-avg F1 score on IEMOCAP dataset?

**Comment by deepanwayx** [comment]
For the earlier two-stage DialogueRNN model, the W-Avg F1 score is 62.75 in IEMOCAP.

**Comment by Columbine21** [comment]
Thanks for your reply! I read your survey. It really helps.
